version: '3.9'
services:
  backend:
    build: .
    container_name: velocix_backend_cont  
    ports:
      - '5000:5000'
    
    volumes:
      - .:/app
      - /app/node_modules
    
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgis/postgis:17-3.5
    container_name: velocix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass 
      POSTGRES_DB: velocixdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    container_name: cointainer_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres_data:
    